Parameters:
  ProjectName:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z]*$
    Default: myproject
Resources:
  CodeRepository:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Ref ProjectName
      RepositoryDescription: !Join [' ', [!Ref ProjectName, 'Project Code Repository']]
  Storage:
    Type: 'AWS::S3::Bucket'
    Properties:
        BucketName: !Ref ProjectName
